### ISSUE TITLE
Choosing tests reading data from Excel in TestNG

### ISSUE THREAD

**Issue by Audrey80** [RocketRaccoon/TestNG-Examples#1]
So, I have 2 sheets - one with names of files and delimiters - getFiles; another -TC-with Number - of Test case, TestCase, Parameter, Include, Column, Method. Include has "y" if you want to include this TC. Column is the number of column that its content will be compared between respective 2 columns from two files from GetFiles - with Expected and Actual results. Method is what exactly will be checked - Equality between 2 arrays - columns from ExpResFile and ActResFile; Not Null values in these arrays; Dispersion - equality within certain margin, say, 10% difference is seen as equal and pass. This % has to be in Parameter column. I know how to make an array from a column in the file and pass 2 such arrays to method equal and see which element is different. Now - how to choose the data from Excel and continue a loop through the whole test set including all tests with "y" and choosing a right method? It is actually comparing columns from 2 csv files with custom delimiters - and the requirement is it has to be in TestNG. Thank you!

**Comment by RocketRaccoon** [comment]
Please correct me, if I wrong

| TestCase | Parameter | Include | Column | Method |
| --- | --- | --- | --- | --- |
| TestCase Name #1 | Fail percent (e.g. 10%) | Yes/No | Link to expected array #1 | Link to TestNG method |
| TestCase Name #2 | Fail percent (e.g. 5%) | Yes/No | Link to expected #2 | Link to TestNG method |

**Comment by Audrey80** [comment]
Hello! In Column and method there are not links, but number of column and name of method. Thank you!

**Comment by RocketRaccoon** [comment]
Yeah, ok.
It seems that the best way for you would be to run TestNG programatically, will back later with concrete ideas on solution.

**Comment by Audrey80** [comment]
Thank you!

**Comment by Audrey80** [comment]
Hello! How are you? meanwhile I tried to write a data provider without the loop, just to read Excel parameters and pass them to get array with column data to soft assert - and I got a strange error 
Data provider mismatch
Method: m([Parameter{index=0, type=[[Ljava.lang.Object;, declaredAnnotations=[]}]) - when I tried to use Object [][] from data provider in test like String aa=(String)P[0][0]; - I need 5 Strings like that to pass paramters like bb=(String)P[0][1], etc - do you know why is that? I started to program actually a month ago :)

**Comment by RocketRaccoon** [comment]
Hi, will try to provide example for you tomorrow.
About your issue - `@DataProvider` returns `Object[][]`. First size shows how many sets of data will be provided. Second is your params of test method.

**Comment by Audrey80** [comment]
Thank you very much, I  really value your help a lot!

**Comment by RocketRaccoon** [comment]
See example, you need to generate xml from xlsx first - just run XmlFromXlsx
And then run tests according to generated xml

**Comment by Audrey80** [comment]
This is marvelous! I had a two days vacation so I saw it only now. My task is to understand it clearly and find external jars to put on my computer. Thank you ever so much!

**Comment by RocketRaccoon** [comment]
All dependecies are managed with gradle, just open it as a gradle project.

**Comment by Audrey80** [comment]
Hello! Judging by the words you are using, it is Maven project  - I have not yet come to this, I tried to run it as Testng and put generated XML file to { workspace}/{project}/src directory as I read on the Internet. But it does not look there for some reason :), it looks into users/AppData/Local/Temp/testng-eclipse-.....\testng-customsuite.xml - can it be done through Run Configuration - to make it look at the place I want?
And in Excel for the first test in writes the data from cells from the third row, the other rows are fine - another puzzle for me :). But this is nothing, the main thing is to place XML file in a proper spot - if it is possible without maven - is it?  Sorry if it sounds stupid, I am a novice...Thank you very much indeed again, it is a great code that you wrote! Being a good programmer is the best thing on earth - do you agree :) ?

**Comment by RocketRaccoon** [comment]
I agree, thanks. Mildly I'm not very familliar with eclipse, I'm using Intellij IDEA. And there I can specify testng.xml which will be pre-generated by XmlFromXlsx class. Also check code where I have skipped first row where I was expecting headers. You can create xml where you want just replace this path `PrintWriter writer = new PrintWriter(new FileOutputStream("build/resources/test/generated_testng.xml"));`. Is this what you are asking about or I missed something?
