### ISSUE TITLE
XML file for testNG

### ISSUE THREAD

**Issue by Audrey80** [RocketRaccoon/TestNG-Examples#2]
Hello! I am trying to open the project for the code you wrote as gradle project, but still there is no build/resources/test/ directory for generated_testng.xml, so tests fail without inputList. When I run it as usual Eclipse, it says it looks for xml file in Appdata\Local\Temp\testng-eclipse...where I can't put a file. So - what do I need to do to put xml file in a right place? Thank you very much again!

**Comment by RocketRaccoon** [comment]
You can change xml output directory [here](https://github.com/RocketRaccoon/TestNG-Examples/blob/master/src/test/java/data/XmlFromXlsx.java#L88) and update TestNG run configuration in eclipse to search in a right place. That's how it looks like in IJ - [link](https://snag.gy/41kWRa.jpg).

**Comment by Audrey80** [comment]
Thank you again very much for your help, I am sorry it does not work for me...I understand that in PrintWriter I can put xml file wherever I want; however, in Eclipse we have Run Configurations where we can define Suite and I tried to do that - to put in Suite the path for XML file as you have in IDEA and still it looks into temporary folder that creates during build so I can't put anything there. I saw in Internet that IDEA is better than Eclipse...

**Comment by RocketRaccoon** [comment]
Yeah, I moved to it few year ago. IJ is more comfortable for development, as for me. Also it would be easier for me to guide you through it.

**Comment by Audrey80** [comment]
I am wandering somewhere close, but...I changed path or XML file to C:/Users/aglen/workspace/GrXml/src/testng.xml; Suite in Run Configurations to the same path; now it says 
"cannot find class in classpath" - and default classpath is {project} - GrXml - which I have? It is in C:\Users\aglen\workspace\GrXml\src\test\java. By the way, a childish question if I may - why do we use  \ or / in the path? \ is Windows and / is UNIX ?

**Comment by RocketRaccoon** [comment]
why do we use \ or / in the path? \ is Windows and / is UNIX ? - yes
Could you share a screencast of what's going on when you are trying to run xml?

**Comment by Audrey80** [comment]
Hello, happy to speak to you. I am getting this - no input parameters because there is no xml file with them - it is created correctly, but I can't make it look at it!
org.testng.TestNGException: 
Parameter 'inputList' is required by @Test on method test1 but has not been marked @Optional or defined
[TestNG] Running:
  C:\Users\aglen\AppData\Local\Temp\testng-eclipse-1407733441\testng-customsuite.xml - this location is created at run time, so I can't put anything in it.  
Thank you very much!

**Comment by RocketRaccoon** [comment]
Could you change build directory in eclipse project settings?
